steps:
  - name: maven:3-jdk-11
    entrypoint: mvn
    args: ['package','-Dmaven.test.skip=true', '-P=PROD']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/${PROJECT_ID}/jirareport:$SHORT_SHA', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push','gcr.io/${PROJECT_ID}/jirareport:$SHORT_SHA']
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['run', 'deploy', 'jirareport', '--region=us-central1', '--platform', 'managed', '--allow-unauthenticated', '--image=gcr.io/${PROJECT_ID}/jirareport:$SHORT_SHA']
options:
  logging: CLOUD_LOGGING_ONLY
